networks:
  moneymaster_network:
    driver: bridge

services:
  moneymaster.apigateway:
    image: ${DOCKER_REGISTRY-}moneymasterapigateway
    container_name: apigateway
    build:
      context: .
      dockerfile: MoneyMaster.APIgateway/MoneyMaster.APIgateway/Dockerfile
    ports:
      - "20001:8081"
      - "20002:8080"
    depends_on:
      - identityservice.webapi
      - moneymasterservice.webapi
    networks:
      - moneymaster_network

  identityservice.webapi:
    image: ${DOCKER_REGISTRY-}identityservicewebapi
    container_name: identity-api
    build:
      context: .
      dockerfile: IdentityService/Hosts/IdentityService.WebAPI/Dockerfile
    ports:
      - "18001:8081"
      - "18002:8080"
    networks:
      - moneymaster_network

  moneymasterservice.webapi:
    image: ${DOCKER_REGISTRY-}moneymasterservicewebapi
    container_name: moneymaster-api
    build:
      context: .
      dockerfile: MoneyMasterService/Hosts/MoneyMasterService.WebAPI/Dockerfile
    ports:
      - "19001:8081"
      - "19002:8080"
    networks:
      - moneymaster_network