networks:
  moneymaster_network:
volumes:
  identityservicedb_data:
  moneymasterservicedb_data:
  pgadminvol:


services:
  moneymaster.apigatewayocelot:
    image: ${DOCKER_REGISTRY-}moneymasterapigatewayocelot
    container_name: apigatewayocelot
    build:
      context: .
      dockerfile: MoneyMaster.APIgateway/MoneyMaster.APIGatewayOcelot/Dockerfile
    ports:
      - "21001:8081"
      - "21002:8080"
    networks:
      - moneymaster_network

  moneymaster.apigateway:
    image: ${DOCKER_REGISTRY-}moneymasterapigateway
    container_name: apigateway
    build:
      context: .
      dockerfile: MoneyMaster.APIgateway/MoneyMaster.APIgateway/Dockerfile
    ports:
      - "20001:8081"
      - "20002:8080"
    depends_on:
      - identityservice.webapi
      - moneymasterservice.webapi
    networks:
      - moneymaster_network

  identityservice.webapi:
    image: ${DOCKER_REGISTRY-}identityservicewebapi
    container_name: identity-api
    build:
      context: .
      dockerfile: IdentityService/Hosts/IdentityService.WebAPI/Dockerfile
    ports:
      - "18001:8081"
      - "18002:8080"
    networks:
      - moneymaster_network

  moneymasterservice.webapi:
    image: ${DOCKER_REGISTRY-}moneymasterservicewebapi
    container_name: moneymaster-api
    build:
      context: .
      dockerfile: MoneyMasterService/Hosts/MoneyMasterService.WebAPI/Dockerfile
    ports:
      - "19001:8081"
      - "19002:8080"
    networks:
      - moneymaster_network

  # DB for MICROSERVICES
  moneymasterservice.db:
    image: "postgres:latest"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    container_name: moneymasterservice.db
    restart: always
    ports:
      - "5433:5432"
    environment: 
      POSTGRES_DB: "moneymasterservice"
      POSTGRES_USER: "postrgesuser"
      POSTGRES_PASSWORD: "12345678"
      PGDATA: /var/lib/potgresql/core
    volumes:
      - moneymasterservicedb_data:/var/lib/potgresql/moneymasterservice
    networks:
      - moneymaster_network
  
  identityservice.db:
    image: "postgres:latest"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    container_name: 'identityservice.db'
    restart: always
    ports:
     - "5434:5432"
    environment: 
      POSTGRES_DB: "identityservice"
      POSTGRES_USER: "postrgesuser"
      POSTGRES_PASSWORD: "12345678"
      PGDATA: /var/lib/postgresql/identityservice
    volumes:
      - identityservicedb_data:/var/lib/postgresql/identityservice 
    networks:
      - moneymaster_network



  moneymaster.db.admin:
    image: dpage/pgadmin4
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    environment:
      PGADMIN_DEFAULT_EMAIL: user@mail.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    ports:
      - "8889:80"
    volumes:
      - pgadminvol:/var/lib/postgresql/pgadmin
    networks:
      - moneymaster_network

  # reactapp:
  #   image: ${DOCKER_REGISTRY-}reactapp
  #   container_name: reactapp
  #   build:
  #       context: ./MoneyMasterFrontend/frontend
  #       dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"
  #   networks:
  #     - moneymaster_network


 